apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: docker
  namespace: metallb-system
spec:
  addresses:
  - METALLB_IP_ADDRESS_RANGE
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: empty
  namespace: metallb-system
