---
apiVersion: v1
kind: Secret
data:
  miniocfg: "W2RlZmF1bHRdCmFjY2Vzc19rZXkgPSBtaW5pb2FkbWluCnNlY3JldF9rZXkgPSBtaW5pb2FkbWluCg=="
metadata:
  labels:
    app.kubernetes.io/name: miniocfg
  name: miniocfg
  namespace: curiefense
type: Opaque
---
apiVersion: v1
kind: Secret
data:
  miniocfg: "W2RlZmF1bHRdCmFjY2Vzc19rZXkgPSBtaW5pb2FkbWluCnNlY3JldF9rZXkgPSBtaW5pb2FkbWluCg=="
metadata:
  labels:
    app.kubernetes.io/name: miniocfg
  name: miniocfg
  namespace: emissary
type: Opaque
