apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: emissary

resources:
  - https://app.getambassador.io/yaml/emissary/3.2.0/emissary-crds.yaml
  - https://app.getambassador.io/yaml/emissary/3.2.0/emissary-emissaryns.yaml
  - logservice.yaml

patchesStrategicMerge:
  - module.yaml
  - deployment.yaml
