apiVersion: getambassador.io/v2
kind: Module
metadata:
  name: ambassador
  namespace: emissary
spec:
  config:
    lua_scripts: |
      local session = require "lua.session_envoy"
      function envoy_on_request(handle)
        handle:headers():add("X-Lua-Added-Request-Header", "foo")
        session.inspect(handle)
      end
      function envoy_on_response(handle)
        handle:headers():add("X-Lua-Added-Response-Header", "bar")
      end
#session.on_response(handle)