apiVersion: getambassador.io/v3alpha1
kind:  Module
metadata:
  name: ambassador
spec:
  config:
    lua_scripts: |
      function envoy_on_request(request_handle)
        request_handle:headers():add("X-Lua-Added-Request-Header", "foo")
      end

      function envoy_on_response(response_handle)
        response_handle:headers():add("X-Lua-Added-Response-Header", "bar")
      end
